<?php
// header('Content-Type: application/json');

include("admin-panel/config/connect.php");
include("admin-panel/config/class.php");

$status = $_POST['txStatus']; //status of the payment

// echo '<br/>Status -> '.$status;

$orderId = $_POST['orderId']; //order Id generated by me 

// echo '<br/>Order Id -> '.$orderId;

$Amount = $_POST['orderAmount']; //order Amount 

// echo '<br/>Amount -> '.$Amount;

$referenceId = $_POST['referenceId']; //Cashfree Unique ref Id

// echo '<br/>Reference Id -> '.$referenceId;

$paymentMode = $_POST['paymentMode']; //Mode of Payemnt selected by the user

// echo '<br/>Payment Mode -> '.$paymentMode;

$txMsg = $_POST['txMsg']; //Massage Incoming from cashfree

// echo '<br/>Text Msg -> '.$txMsg;

$txTime = $_POST['txTime']; //Payment Timestamp Occurder in cashfree

// echo '<br/>txTime -> '.$txTime;

$signature = $_POST['signature']; //Payment Signature

// echo '<br/>Signature -> '.$signature;

//sending sms
$N = new master();
$r = $N->fetch_job_application_by_order_id($orderId);
for($i=0;$i<sizeof($r);$i++){
  $customerPhone = $r[$i]['phone1']; //phone nymber of the customer
  $app_id = $r[$i]['AppId'];
  $post = $r[$i]['postname'];
}

function sentjobsms($app_id, $customerPhone,$post){
              
    $temp = substr($customerPhone, -10);
    $mobile = '91'.$temp;
        
    $curl = curl_init();
            
    curl_setopt_array($curl, array(
      CURLOPT_URL => "https://api.msg91.com/api/v5/flow/",
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => "",
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 30,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => "POST",
      CURLOPT_POSTFIELDS => "{\n  \"flow_id\": \"613d877b24f2de07cb68b720\",\n  \"sender\": \"fisser\",\n  \"mobiles\": \"$mobile\",\n  \"POST\": \"$post\",\n  \"AID\": \".$app_id.\"\n}",
      CURLOPT_HTTPHEADER => array(
        "authkey: 332829AzzIWu5R9W61249cbfP1",
        "content-type: application/JSON"
      ),
    ));
            
    $response = curl_exec($curl);
    $err = curl_error($curl);
            
    curl_close($curl);
            
    if ($err) {
      echo "cURL Error #:" . $err;
    } else {
      //   echo $response;
    } 
}


//Now, we have to store the data into a payment database which contain all the payment releted data with user information

$core = core::getInstance();
$query = "UPDATE `Payment_details` SET `status` = '$status', `amount` = '$Amount', `ref_id` = '$referenceId', `pmode` = '$paymentMode', `msg` = '$txMsg', `time` = '$txTime' WHERE `Payment_details`.`order_id` = '$orderId';";
$stmt = $core->dbh->prepare($query);
if($stmt->execute()){
    //we have stored the payment status in local database
    //checking the payment is successfull
    if($status == 'SUCCESS'){
        
        sentjobsms($app_id, $customerPhone,$post);
        
        
?>
        <div style="display: flex;align-items: center;justify-content: center;height: 100%;width: 100%;">
          <div style="text-align:center">
            <h1><?php echo $txMsg; ?></h1>
            <img src="https://oaec.org/wp-content/plugins/fundlycrm/assets/images/npe-redirecting.gif" style="width:80%"/>
            <p>Redirecting To Homepage</p>
          </div>
        </div>
        <script>
            setTimeout(function() {
                window.location.href="Print_Application.php?appId=<?php echo $app_id; ?>";
            }, 5000);
        </script>
<?
    }
    else{
?>
        <div style="display: flex;align-items: center;justify-content: center;height: 100%;width: 100%;">
          <div style="text-align:center">
            <h1><?php echo $txMsg; ?></h1>
            <img src="https://oaec.org/wp-content/plugins/fundlycrm/assets/images/npe-redirecting.gif" style="width:80%"/>
            <p>Redirecting To Homepage</p>
          </div>
        </div>
        <script>
            setTimeout(function() {
                window.location.href="index.php";
            }, 10000);
        </script>
<?php
    }
}
else{
?>
        <div style="display: flex;align-items: center;justify-content: center;height: 100%;width: 100%;">
            <h1>Payment Failed !</h1>
        </div>
        <script>
            setTimeout(function() {
                window.location.href="index.php";
            }, 10000);
        </script>

<?php    
}

//echo json_encode($_POST);
?>